# Generated by Django 3.2.9 on 2021-11-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('team_name', models.CharField(max_length=50)),
                ('player_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('tie', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.IntegerField(default=0)),
                ('venue', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('opp_team', models.CharField(max_length=100)),
            ],
        ),
    ]
