# Generated by Django 3.2.9 on 2021-11-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211114_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
