# Generated by Django 3.2.9 on 2021-11-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_timetable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
