# Generated by Django 3.2.9 on 2021-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_teams_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('tie', models.IntegerField()),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
