# Generated by Django 3.2.9 on 2021-11-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_teaminfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
